syntax on
set autoindent
set expandtab
set number
set shiftwidth=2
set softtabstop=2
set bs=indent,eol,start
set so=999
set clipboard=unnamedplus
filetype plugin indent on
let g:terraform_fmt_on_save=1
let g:terraform_align=1
let g:netrw_dirhistmax = 0
let g:vimtex_quickfix_mode=0
set conceallevel=1
