#!/bin/bash

# Receipt API - Example Requests
# This file contains example curl commands for testing the Receipt API
# Make sure the server is running before executing these commands

API_URL="http://localhost:8080/api/v1"

echo "=========================================="
echo "Receipt API - Example Requests"
echo "=========================================="
echo ""

# Health Check
echo "1. Health Check"
echo "Command: GET /api/v1/health"
curl -X GET "$API_URL/health" \
  -H "Content-Type: application/json"
echo -e "\n\n"

# Create Receipt 1
echo "2. Create Receipt (James)"
echo "Command: POST /api/v1/receipts"
RESPONSE1=$(curl -s -X POST "$API_URL/receipts" \
  -H "Content-Type: application/json" \
  -d '{
    "store_name": "Example Supermarket",
    "location": {
      "address": "123 Example Street, Cityville, Country"
    },
    "purchase_date": "2023-09-29",
    "subtotal": 10.47,
    "tax": 0.73,
    "total": 11.20,
    "user": "James",
    "receipt_image_path": "https://example.com/images/receipt/1234567890.jpg"
  }')
echo "$RESPONSE1" | jq .
RECEIPT_ID=$(echo "$RESPONSE1" | jq -r '.id')
echo -e "\n"

# Create Receipt 2
echo "3. Create Another Receipt (James)"
echo "Command: POST /api/v1/receipts"
RESPONSE2=$(curl -s -X POST "$API_URL/receipts" \
  -H "Content-Type: application/json" \
  -d '{
    "store_name": "Best Buy Electronics",
    "location": {
      "address": "456 Tech Avenue, Silicon Valley, USA"
    },
    "purchase_date": "2023-09-30",
    "subtotal": 299.99,
    "tax": 29.99,
    "total": 329.98,
    "user": "James",
    "receipt_image_path": "https://example.com/images/receipt/0987654321.jpg"
  }')
echo "$RESPONSE2" | jq .
RECEIPT_ID2=$(echo "$RESPONSE2" | jq -r '.id')
echo -e "\n"

# Create Receipt 3 (Different User)
echo "4. Create Receipt (Sarah)"
echo "Command: POST /api/v1/receipts"
RESPONSE3=$(curl -s -X POST "$API_URL/receipts" \
  -H "Content-Type: application/json" \
  -d '{
    "store_name": "Coffee Shop Deluxe",
    "location": {
      "address": "789 Brew Lane, Espresso City, Italy"
    },
    "purchase_date": "2023-10-01",
    "subtotal": 5.50,
    "tax": 0.50,
    "total": 6.00,
    "user": "Sarah",
    "receipt_image_path": "https://example.com/images/receipt/coffeereceipt.jpg"
  }')
echo "$RESPONSE3" | jq .
echo -e "\n"

# Get Specific Receipt
echo "5. Get Specific Receipt"
echo "Command: GET /api/v1/receipts/{id}"
curl -s -X GET "$API_URL/receipts/$RECEIPT_ID" \
  -H "Content-Type: application/json" | jq .
echo -e "\n"

# Update Receipt
echo "6. Update Receipt (Partial Update)"
echo "Command: PUT /api/v1/receipts/{id}"
curl -s -X PUT "$API_URL/receipts/$RECEIPT_ID" \
  -H "Content-Type: application/json" \
  -d '{
    "store_name": "Updated Supermarket Name",
    "subtotal": 12.50
  }' | jq .
echo -e "\n"

# Get User Receipts
echo "7. Get All Receipts for User (James)"
echo "Command: GET /api/v1/receipts/user/James"
curl -s -X GET "$API_URL/receipts/user/James" \
  -H "Content-Type: application/json" | jq .
echo -e "\n"

# Get User Receipts (Different User)
echo "8. Get All Receipts for User (Sarah)"
echo "Command: GET /api/v1/receipts/user/Sarah"
curl -s -X GET "$API_URL/receipts/user/Sarah" \
  -H "Content-Type: application/json" | jq .
echo -e "\n"

# Delete Receipt
echo "9. Delete Receipt"
echo "Command: DELETE /api/v1/receipts/{id}"
curl -s -X DELETE "$API_URL/receipts/$RECEIPT_ID2" \
  -H "Content-Type: application/json"
echo "✓ Receipt deleted (204 No Content response)"
echo -e "\n"

# Try to get deleted receipt
echo "10. Try to Get Deleted Receipt (Should return 404)"
echo "Command: GET /api/v1/receipts/{id} (for deleted receipt)"
curl -s -X GET "$API_URL/receipts/$RECEIPT_ID2" \
  -H "Content-Type: application/json" | jq .
echo -e "\n"

# Summary
echo "=========================================="
echo "Example Complete!"
echo "=========================================="
echo "Notes:"
echo "- All timestamps are in UTC/RFC3339 format"
echo "- IDs are UUIDs generated by the database"
echo "- Dates are in YYYY-MM-DD format"
echo "- Prices are in decimal format (2 decimal places)"
echo "=========================================="
