#! /bin/sh
BRIGHTNESS=$(xrandr --verbose| grep Brightness | awk '{print $2}'| head -n 1)
if [ "$1" = "up" ]; then
  for screen in $(xrandr | grep " connected" | awk '{print $1}'); do
    xrandr --output $screen --brightness $(bc <<< "$BRIGHTNESS+ 0.1");
  done
else
  for screen in $(xrandr | grep " connected" | awk '{print $1}'); do
    xrandr --output $screen --brightness $(bc <<< "$BRIGHTNESS- 0.1");
  done
fi
